### ISSUE TITLE
第一次启动显示无信号源

### ISSUE THREAD

**Issue by rilyuuj** [lucifersun/China-Telecom-ShangHai-IPTV-list#1]
你好，感谢您抽取了IPTV的地址列表。
我是用您的地址列表导入到HDP上使用，但是第一次打开自定义（列表导入）后会显示无信号源，切换频道后有几率恢复正常。
不知道是否是电信做了IP更新，望作者能提供获取源地址的方法，谢谢

**Comment by lucifersun** [comment]
地址列表没有变化，如果有变化，我会尽快更新数据的。
因为我手头没有Android机顶盒，所以没办法测试HDP，这个只能抱歉了。
至于播放地址，利用端口镜像，将机顶盒与电信路由器之间的数据转发出来抓包即可。

**Comment by yangjuniori** [comment]
有上海IPTV标清  对比发现有的频道还没有比如 七彩戏剧   我需要什么设备能获得频道地址

**Comment by lucifersun** [comment]
频道缺失有2个可能，一个是我整理列表的时候遗漏了，因为抓包出来的数据里有些地址标注名称和频道名称对不上，你可以看一下这个原始文件。
[https://github.com/lucifersun/China-Telecom-ShangHai-IPTV-list/blob/master/TCP%20Steam%20receive.txt](url)
还有一个可能就是这个频道没有提供回看。实际上这些rtsp地址都是回放地址，直播用的是igmp。如果一个频道不提供回看，就没有对应的rtsp。
看到有人用igmpproxy来实现电脑端看直播，但直播的数据源是在IPTV的专用vlan上，不像rstp通过Internet直接就能看，比较局限，所以我也没有深入研究。
