### ISSUE TITLE
上海教育电视台 无法播放？

### ISSUE THREAD

**Issue by wnpllrzodiac** [lucifersun/China-Telecom-ShangHai-IPTV-list#12]
rtsp://124.75.34.37/PLTV/88888888/224/3221226088/00000100000000060000000000007667_0.smil?playseek=20180518220000-20180519130000

rtsp://124.75.34.37/PLTV/88888888/224/3221226088/00000100000000060000000000007667_0.smil

playseek 加不加都无法播放。这段时间视频文件需要急用，望速回，谢谢！

**Comment by lucifersun** [comment]
播放正常

![snipaste_2018-05-19_13-42-59](https://user-images.githubusercontent.com/13460262/40265416-92f30628-5b6a-11e8-8644-3fd35a4afdb4.JPG

**Comment by wnpllrzodiac** [comment]
可能是电信移动网络的限制，抱歉，麻烦你了。已经可以录制了。还是非常感谢您提供的资源！
