### ISSUE TITLE
实测 Android Kodi 17.2 支持 m3u

### ISSUE THREAD

**Issue by road2002** [lucifersun/China-Telecom-ShangHai-IPTV-list#15]
软硬件：Sony 电视自带 Android 7.0, Kodi 17.2 with Simple PVR 插件
结论：载入M3U列表完美播放 （不是m3u8）
request：
1 生成m3u的页面，能否增加hd去重的选项（有hd源的时候不再生成sd源）
2 是否可能增加epg

**Comment by lucifersun** [comment]
hd去重可以做，这两天抽空加上
epg搞不定，至少我的水平搞不定啊

**Comment by jdnx** [comment]
@lucifersun  今日偶然发现最近增加了不少高清频道, ICS, 星尚, 中国教育,几个卫视, 不知道能否重新抓下,谢谢

**Comment by lucifersun** [comment]
已添加去重

**Comment by lucifersun** [comment]
ICS, 星尚, 中国教育…………这些频道早就有了，但只有直播。
没回放功能就没有rtsp地址，除非你有IPTV业务，然后在B平面上搭组播代理转发，才能在其它设备上看直播频道。
