### ISSUE TITLE
又有部分频道源已经失效

### ISSUE THREAD

**Issue by robertshan** [lucifersun/China-Telecom-ShangHai-IPTV-list#16]
是否能够定期来检查频道源是否发生变化？

**Comment by lucifersun** [comment]
请告知失效频道，thx

**Comment by xiw9** [comment]
五星体育HD？
rtsp://124.75.34.37/PLTV/88888888/224/3221226234/10000100000000060000000000813434_0.smil?playseek=20180620204000-20180621004000

**Comment by robertshan** [comment]
就是想看五星体育，楼上真效率

**Comment by lucifersun** [comment]
地址没变，刚才可能是电信服务器问题。
之前我试了一下确实不能播放，重新抓包发现地址没变，再次尝试发现又能播放了。
