### ISSUE TITLE
第一财经HD是不是打不开

### ISSUE THREAD

**Issue by witchkk** [lucifersun/China-Telecom-ShangHai-IPTV-list#24]
好像别的频道都行  就第一财经HD 直播和回放都不行?

**Comment by lucifersun** [comment]
测试正常

**Comment by witchkk** [comment]
请教下 第一财经HD是用什么播放器合适的    我用POT  后面加时间,不加时间 都是服务器关闭 别的台都行

**Comment by lucifersun** [comment]
很大可能是服务器问题，列表里的地址并非实际视频服务器的地址。
以前抓过包，实际访问的时候还要跳转1-2次才能到达最终的服务器，但服务器IP并不固定，估计是做了负载均衡。
你这个情况有可能就是第一财经HD这个频道被跳转到一个工作不正常的服务器上。

**Comment by witchkk** [comment]
原来如此 学习了 感谢指点

**Comment by mafamily2496** [comment]
所以是需要多连几次才能连上吗

**Comment by lucifersun** [comment]
可以尝试换IP后重连，不确定电信的分流设置
