### ISSUE TITLE
能否给出给出VLAN 85小内网内加载节目列表的接口

### ISSUE THREAD

**Issue by ihipop** [lucifersun/China-Telecom-ShangHai-IPTV-list#30]
已经做好了 VLAN 85的网络 现在也能访问这个小内网，但是运营商可能换回放地址，我想机顶盒肯定也不不会固化这些播放地址，肯定开机的时候去请求一个接口返回所有的这些播放地址，现在家里没有IPTV的机顶盒，能否给出这个提取的地址？我想不会靠一个一个换台抓的吧？

**Comment by lucifersun** [comment]
基本上不会变，至少3年前到现在，没变过

**Comment by ihipop** [comment]
@lucifersun 我现在看这个必须带上时间起止， 否则放不了，现在看直播都用组播了。
这种回放的以前可以不带时间吗？

**Comment by lucifersun** [comment]
回放链接带时间的兼容性好，有些高清频道不带时间放不了。

**Comment by ihipop** [comment]
@lucifersun 我用vlc播放的时候抓包看了，不带时间的服务器都不返回播放数据。类似的，perfect player，友窝直播 都一样。这个时间起点还不能太早，早了也放不了，但是可以到未来很长时间
