### ISSUE TITLE
IPTV直播源是长期有效的吗？

### ISSUE THREAD

**Issue by donny861221** [lucifersun/China-Telecom-ShangHai-IPTV-list#4]
IPTV直播源是长期有效的吗？还是过段时间就地址就失效了，需要经常更新直播地址的？
能做一份可以网络盒子直播APP上用的TXT的么，可以自定义频道用

**Comment by lucifersun** [comment]
时效不清楚，反正从我抓包出来数据到现在，没变过。
TXT文件么，根据你的需要，m3u8改下格式不行吗？

**Comment by donny861221** [comment]
希望能地址长期有效，因为我看了下你以前的，好像直播源地址过断时间就会更新一次的
可以更改，我已经改好了，就是比较麻烦
不管怎么样，都谢谢了，让我看上了IPTV，原来网络盒子加那些直播APP，要么网络卡，清晰度也低，还经常源失效

**Comment by lucifersun** [comment]
增加频道，原有频道的地址没变化

**Comment by qwervbnm** [comment]
@lucifersun 真心感谢经常更新直播源，已享用一年多了。如果没记错的话，最早有看到你写的如何获取魔都电信直播源地址的教程，虽然本人尝试最终没成功，还好这里有更新，可以直接用。

另，推荐安卓平台可用APP--“超级直播”，我用安卓盒子实测，所有频道都可以流畅播放，并且自带时移。导入需要TXT文件，格式为”频道名,地址“，也可以通过链接导入。所以有需求，如果有同步更新TXT文件的话就能一键在线导入了。

**Comment by lucifersun** [comment]
都要txt文件？文件里面是什么格式的？

**Comment by qwervbnm** [comment]
[IPTV.txt](https://github.com/lucifersun/China-Telecom-ShangHai-IPTV-list/files/1818533/IPTV.txt)
@lucifersun 就是每行一个”频道名,地址“

**Comment by lucifersun** [comment]
已添加IPTV.txt
