### ISSUE TITLE
安卓网络盒子上电视剧频道HD的放不了

### ISSUE THREAD

**Issue by donny861221** [lucifersun/China-Telecom-ShangHai-IPTV-list#5]
但是别人苹果设备可以，请问怎么解决

**Comment by lucifersun** [comment]
Android上播放HD频道，对软硬件要求颇高。
至少我测试下来，三星S7和SONY Z3 Tables，使用MXplayer，开启“硬解+”，5G WiFi，可以流畅播放HD频道，但缺一不可。
