### ISSUE TITLE
.smil里面有个播放5分钟的限制，怎么弄能去掉？

### ISSUE THREAD

**Issue by lkmvip** [lucifersun/China-Telecom-ShangHai-IPTV-list#9]
.smil里面有个播放5分钟的限制，怎么弄能去掉？

**Comment by lkmvip** [comment]
RTSP源因为很多播放器不会自动缓冲，所以.smil后缀的RTSP里面都被运营商做了手脚，时间从几秒钟到几分钟不等，上海电信是5分钟后停止播放，除非加了playseek，但是playseek又要加开始时间，这样的话不能做到实时播放了

**Comment by lkmvip** [comment]
测试的安卓播放器是mxplayer，KODI
另外超级直播应该能缓冲rtsp吧，不会断流，但是界面很不友好，所以想探讨一下怎么去除他5分钟播放限制

**Comment by lkmvip** [comment]
反复测试后确定，加playseek也没法达到长效播放

除非安卓用用超级直播，这个可以不断流

**Comment by lkmvip** [comment]
能不能抓包看看，IPTV上点击播放后还带了什么参数

**Comment by lucifersun** [comment]
没发现这个情况啊，刚才特地测试了一下。手机（S7edge）上用mxplayer，PC上用KODI、potplayer，都能顺利播放超过5分钟。
昨天晚上用potplayer看F1，2个小时妥妥的。
记得曾经有一次用Android平板看F1直播，一场比赛完整看下来也没什么问题。
也都没有加playseek参数。

**Comment by lucifersun** [comment]
会不会是盒子的网络断流了？如果是HD频道，对WiFi要求还是挺高的，至少我这台S7edge，必须5G WiFi才能流畅播放。

**Comment by lkmvip** [comment]
不会，手机和盒子全都是5分钟断，正好5分钟不差一分一秒，分别接2个路由器全都是5G频段，所以能排除手机，盒子以及路由器的故障，并且盒子上装了超级直播也能长时间播放

同时我电脑potplayer也能长时间播放

**Comment by lkmvip** [comment]
前面测试了EasyPlayerPro能播放超过5分钟，EasyPlayer是专门为这种网络流设计的播放器，可惜安卓的IPTVapp不能直接呼出这个程序，看个IPTV好复杂

**Comment by lkmvip** [comment]
上海电信的这个rtsp太奇怪了，刚才抓包看了一下，链接到124.75.34.37之后，会重新定向到下一级服务器，再从下一级服务器定向到真实播放服务器

顺便也测试了VLC，别的地区的rtsp都直接能播放，VLC直接播放124.75.34.37是无效的，但是改成真实服务器地址是能放的，上海电信真的太奇怪了

**Comment by lucifersun** [comment]
刚才看了一下，直接跳转到了124.75.35.33:554这个地址，测试下来所有频道都可以用这个地址来播放。
感觉124.75.34.37就是做了一个负载均衡的分流。

**Comment by lkmvip** [comment]
是的，会找负载最低的服务器来播放，所以直接锁定实际地址不现实，看来还是得找软件开发商解决

**Comment by lucifersun** [comment]
试了一段时间，感觉实际地址虽然会变换，但几个IP都是有效的。理论上可以替换IP之后直接用实际地址来播放。但这样一来，几台服务器的负载均衡就失效了，如果不是特别必要，建议还是不要这么做。

**Comment by snoopyhzy** [comment]
> 试了一段时间，感觉实际地址虽然会变换，但几个IP都是有效的。理论上可以替换IP之后直接用实际地址来播放。但这样一来，几台服务器的负载均衡就失效了，如果不是特别必要，建议还是不要这么做。

我试了好像不是这样的，那个不带playseek的地址，不是从34.37首先跳一次过去，如果直接打开经常不能播放，一定要34.37 rtsp 302一次才能播放。
电脑端用vlc播放测试的。
跳至少有3个/23网段，我是直接在iptv专网播放的，这里比在internet稳定很多。
